<a href="https://colab.research.google.com/github/shimant01/CSE-413-Simulation-Modeling-Lab/blob/main/SIM_Lab1_shimanto_046.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Scalar & Array Operations (Redo Section with Your Own Values):

*  Run the given code with
scalar = 3.7 and a new array of at least 6 elements.

*  Show outputs of all built-in mathematical functions (sin, cos, tan, etc.).


In [8]:

import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Sample scalar and array inputs
scalar =3.7
arr=np.array([1,3,4,6,2,2])

#built-in mathematical functions (sin, cos, tan, etc.).
sin_val=np.sin(arr)
cos_val=np.cos(arr)
tan_val=np.tan(arr)
asin_val=np.arcsin(np.clip(arr/np.max(arr),-1,1))
acos_val=np.arccos(np.clip(arr/np.max(arr),-1,1))
atan_val=np.arctan(np.clip(arr/np.max(arr),-1,1))
print("sin:", sin_val)
print("cos:", cos_val)
print("tan:", tan_val)
print("asin:", asin_val)
print("acos:", acos_val)
print("atan:", atan_val)

sin: [ 0.84147098  0.14112001 -0.7568025  -0.2794155   0.90929743  0.90929743]
cos: [ 0.54030231 -0.9899925  -0.65364362  0.96017029 -0.41614684 -0.41614684]
tan: [ 1.55740772 -0.14254654  1.15782128 -0.29100619 -2.18503986 -2.18503986]
asin: [0.16744808 0.52359878 0.72972766 1.57079633 0.33983691 0.33983691]
acos: [1.40334825 1.04719755 0.84106867 0.         1.23095942 1.23095942]
atan: [0.16514868 0.46364761 0.5880026  0.78539816 0.32175055 0.32175055]




2. 2×2 Matrix Calculations (Already Done in Class):
Study and understand the example code given for trigonometric, exponential, logarithmic, and rounding operations on a 2×2 matrix.


Task: Apply the Same Operations on a 3×2 Matrix
Create a 3×2 matrix with custom values.
Perform and display results of:

 * Trigonometric functions
* Exponential & logarithmic functions


* Absolute value & square root

*   Remainder when divided by 2



* Rounding (round, floor, ceil)


📌 Make sure to clip inputs where needed to avoid math errors (e.g., arcsin/arccos domain issues).


In [7]:
import numpy as nd
from sympy import Matrix
import matplotlib.pyplot as plt
import  seaborn as sns

mat=np.array([[1,3],[4,6],[2,2]])
#Trigonometric functions
sin_val=np.sin(mat)
cos_val=np.cos(mat)
tan_val=np.tan(mat)
asin_val=np.arcsin(np.clip(mat/np.max(mat),-1,1))
acos_val=np.arccos(np.clip(mat/np.max(mat),-1,1))
atan_val=np.arctan(np.clip(mat/np.max(mat),-1,1))

#Exponential & logarithmic functions
exp_val=np.exp(mat)
log_val=np.log(mat)

#Absolute value & square root
abs_val=np.abs(mat)
sqrt_val=np.sqrt(mat)

#Remainder when divided by 2
rem_val=np.remainder(mat,2)

#Rounding (round, floor, ceil)
round_val=np.round(mat)
floor_val=np.floor(mat)
ceil_val=np.ceil(mat)

# Display results
print("Matrix:\n", mat)
print("\nsin:\n", sin_val)
print("\ncos:\n", cos_val)
print("\ntan:\n", tan_val)
print("\nasine:\n", asin_val)
print("\nacosine:\n", acos_val)
print("\natangent:\n", atan_val)
print("\nexp:\n", exp_val)
print("\nlog (natural):\n", log_val)
print("\nabs:\n", abs_val)
print("\nsqrt:\n", sqrt_val)
print("\nrem (remainder when divided by 2):\n", rem_val)
print("\nround:\n", round_val)
print("\nfloor:\n", floor_val)
print("\nceil:\n", ceil_val)


Matrix:
 [[1 3]
 [4 6]
 [2 2]]

sin:
 [[ 0.84147098  0.14112001]
 [-0.7568025  -0.2794155 ]
 [ 0.90929743  0.90929743]]

cos:
 [[ 0.54030231 -0.9899925 ]
 [-0.65364362  0.96017029]
 [-0.41614684 -0.41614684]]

tan:
 [[ 1.55740772 -0.14254654]
 [ 1.15782128 -0.29100619]
 [-2.18503986 -2.18503986]]

asine:
 [[0.16744808 0.52359878]
 [0.72972766 1.57079633]
 [0.33983691 0.33983691]]

acosine:
 [[1.40334825 1.04719755]
 [0.84106867 0.        ]
 [1.23095942 1.23095942]]

atangent:
 [[0.16514868 0.46364761]
 [0.5880026  0.78539816]
 [0.32175055 0.32175055]]

exp:
 [[  2.71828183  20.08553692]
 [ 54.59815003 403.42879349]
 [  7.3890561    7.3890561 ]]

log (natural):
 [[0.         1.09861229]
 [1.38629436 1.79175947]
 [0.69314718 0.69314718]]

abs:
 [[1 3]
 [4 6]
 [2 2]]

sqrt:
 [[1.         1.73205081]
 [2.         2.44948974]
 [1.41421356 1.41421356]]

rem (remainder when divided by 2):
 [[1 1]
 [0 0]
 [0 0]]

round:
 [[1 3]
 [4 6]
 [2 2]]

floor:
 [[1. 3.]
 [4. 6.]
 [2. 2.]]

ceil:
 [[1. 3

3. Vector Functions
Understand the operations on the 1D vector shown in the notebook.


Task: Perform Same Operations on a 2×3 Matrix
Your 2×3 matrix can have float values (e.g., 2.1, 4.7…).


Implement and display:


* Max & Min (with indices)


* Vector length


* Sorted version (both row-wise descending and entire matrix descending)


* Sum, Product


* Median, Mean, Standard Deviation


In [6]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

vec=np.array([[1.3,4.6,2.2],[5.0,3.5,4.4]])

#Max & Min (with indices)
max_val=np.max(vec)
max_index=np.argmax(vec)
min_val=np.min(vec)
min_index=np.argmin(vec)

#Vector length
vec_length=len(vec)

#Sorted version (both row-wise descending and entire matrix descending)
sorted_vec=np.sort(vec,axis=1)
flatten_vec = np.sort(vec.flatten())

#Sum, Product
sum_val=np.sum(vec)
prod_val=np.prod(vec)

#Median, Mean, Standard Deviation
median_val=np.median(vec)
mean_val=np.mean(vec)
std_dev=np.std(vec)

# Display results
print("Max value:", max_val, "at index", max_index)
print("Min value:", min_val, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sum of elements:", sum_val)
print("Product of elements:", prod_val)
print("Median value:", median_val)
print("Mean value:", mean_val)
print("Standard deviation:", std_dev)


Max value: 5.0 at index 3
Min value: 1.3 at index 0
Length of vector: 2
Sorted vector: [[1.3 2.2 4.6]
 [3.5 4.4 5. ]]
Sum of elements: 21.0
Product of elements: 1013.0120000000002
Median value: 3.95
Mean value: 3.5
Standard deviation: 1.3416407864998738
